In [34]:
import numpy as np




from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
import tensorflow as tf
from sklearn.compose import ColumnTransformer

In [47]:
#load the dataset
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target


In [43]:
from sklearn.model_selection  import train_test_split
#split the train data and test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3 ,random_state=42)

In [44]:
from sklearn.preprocessing import StandardScaler
# StandardScaler 
scatter=StandardScaler() 
x_train=scatter.fit_transform(x_train)#(x - mean/std) calculate internally and transform 
x_test=scatter.transform(x_test)

In [45]:
from sklearn.preprocessing import OneHotEncoder
# OneHotEncoder
y_train=tf.keras.utils.to_categorical(y_train)#coverting the data into binary formate
y_test=tf.keras.utils.to_categorical(y_test)

In [39]:
# multiple layers perceptron
model=tf.keras.Sequential([
    tf.keras.layers.Dense(units=64,activation="relu",input_shape=(x_train.shape[1],)),
    tf.keras.layers.Dense(units=64,activation="relu"),
    tf.keras.layers.Dense(units=3,activation="softmax")
                          ])

C:\Users\sivau\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [40]:
# complile model
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [41]:
# train  model
model.fit(x_train,y_train,epochs=5,batch_size=32)

Epoch 1/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 835us/step - accuracy: 0.4363 - loss: 1.0709
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8384 - loss: 0.9667 
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8168 - loss: 0.8746 
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.8273 - loss: 0.7929  
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8436 - loss: 0.7155 


In [42]:
# Evaluate the model 
y_pred = np.argmax(model.predict(x_test), axis=-1) 
y_test_labels = np.argmax(y_test, axis=-1) 
accuracy = accuracy_score(y_test_labels, y_pred) 
print(f'Accuracy: {accuracy*100:.2f}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Accuracy: 84.44


In [10]:
from sklearn.preprocessing import StandardScaler
import numpy as np


In [11]:
age= np.array([16,40,72,100]).reshape(-1,1)

In [12]:
age

array([[ 16],
       [ 40],
       [ 72],
       [100]])

In [13]:
np.mean(age)

57.0

In [14]:
np.std(age)

31.796226191169293

In [15]:
age.std()

31.796226191169293

In [16]:
sc= StandardScaler()

In [17]:
sc.fit(age)

StandardScaler()

In [18]:
sc.mean_

array([57.])

In [19]:
sc.var_

array([1011.])