In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [2]:
# sigmoid activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
# derivative of sigmoid function
def sigmoid_derivative(x):
    return x*(1-x)

In [4]:
# input and output data (xor problem)
inputs=np.array([[0,0],[0,1],[1,0],[1,1]])
# output values
output=np.array([[0],[1],[1],[0]])


In [5]:
# intialize the weights randomly
input_layer_neuron=inputs.shape[1]
hidden_layer_neurons=2
output_layer_neurons=1

# hidden_weights=np.random.uniform(size=(input_layer_neuron,hidden_layer_neurons))
# hidden_bias=np.random.uniform(size=(1,hidden_layer_neurons))

In [27]:
hidden_weights=np.random.uniform(low=0,high=0.7,size=(input_layer_neuron,hidden_layer_neurons))
hidden_bias=np.random.uniform(low=0,high=0.7,size=(output_layer_neurons,hidden_layer_neurons))

In [28]:
hidden_layer_neurons
# hidden_weights

2

In [29]:
input_layer_neuron

2

In [30]:
output_layer_neurons

1

In [31]:
hidden_weights

array([[0.42351814, 0.27429537],
       [0.31741711, 0.11968981]])

In [32]:
hidden_bias

array([[0.13446762, 0.21550665]])

In [33]:
output_weights=np.random.uniform(low=0,high=1,size=(hidden_layer_neurons,output_layer_neurons))
output_bias=np.random.uniform(low=0,high=1,size=(1,output_layer_neurons))

In [34]:
# learning rate
lr=0.1

In [2]:
# train the neural_network
for epoch in range(1000):
#     feedforward
    hidden_layer_input=np.dot(inputs,hidden_weights)+hidden_bias
    hidden_layer_output=sigmoid(hidden_layer_input)
    output_layer_input=np.dot(hidden_layer_input,output_weights)+output_bias
    predicted_output=sigmoid(output_layer_input)
    
#     backpropagation
    error=output-predicted_output
    d_predicted_output=error*sigmoid_derivative(predicted_output)
    
    error_hidden_layer=d_predicted_output.dot(output_weights.T)
    d_hidden_layer=error_hidden_layer*sigmoid_derivative(hidden_layer_output)
    
#     update the weights and bias
    output_weights=output_weights+hidden_layer_output.T.dot(d_predicted_output)*lr
    output_bias+=np.sum(d_predicted_output,axis=0,keepdims=True)*lr
    
    hidden_weights+=inputs.T.dot(d_hidden_layer)*lr
    hidden_bias+=np.sum(d_hidden_layer,axis=0,keepdims=True)*lr
    
# final output

NameError: name 'inputs' is not defined

In [36]:
print("Final output after training:")
print(predicted_output)

Final output after training:
[[0.47539444]
 [0.49619309]
 [0.50495394]
 [0.52574977]]


In [42]:
output_weights.T,predicted_output


(array([[0.21167269, 0.15056119]]),
 array([[0.47539444],
        [0.49619309],
        [0.50495394],
        [0.52574977]]))

In [16]:
# accuracy_score??

In [44]:
np.dot(inputs,hidden_weights)

array([[0.        , 0.        ],
       [0.33146525, 0.08709023],
       [0.40592316, 0.21507894],
       [0.73738841, 0.30216917]])